### ISSUE TITLE
The links isn´t work

### ISSUE THREAD

**Issue by DevAugusto** [Giorgiark/affirmationclock2.0#1]
Hello Dear!

Anything link can i find on your Git isn´t working for me, its my internet connection or a bug?

![image](https://github.com/user-attachments/assets/8abbfb7a-28d5-4224-a048-823904438c7f)

**Comment by Giorgiark** [comment]
Work perfectly on mine
<img width="1440" alt="Screenshot 2024-11-03 alle 11 13 35" src="https://github.com/user-attachments/assets/3afde3cd-e232-4510-9b99-ef79dad8d4fc">

**Comment by DevAugusto** [comment]
It works again, thanks!!!
